### ISSUE TITLE
TypeError: Body is unusable

### ISSUE THREAD

**Issue by ruibaby** [ShenQingchuan/github-contributor-svg-generator#2]
log:

```bash
❯ pnpx make-github-contributor-svg -t <PROTECTED> -o halo-dev -r halo
Library/pnpm/store/v3/tmp/dlx-2942       |  WARN  deprecated request@2.88.2
 WARN  GET https://registry.npmjs.org/stdin-discarder error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Library/pnpm/store/v3/tmp/dlx-2942       |  WARN  deprecated har-validator@5.1.5
Library/pnpm/store/v3/tmp/dlx-2942       |  WARN  deprecated uuid@3.4.0
 WARN  GET https://registry.npmjs.org/asn1 error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Library/pnpm/store/v3/tmp/dlx-2942       | +221 ++++++++++++++++++++++
Library/pnpm/store/v3/tmp/dlx-2942       | Progress: resolved 242, reused 221, downloaded 0, added 221, done
✔ Fetching pull requests done
✔ Fetching commits done
✔ Supplementing commits done
⠏ Generating SVG file...node:internal/deps/undici/undici:6466
        throw new TypeError("Body is unusable");
              ^

TypeError: Body is unusable
    at specConsumeBody (node:internal/deps/undici/undici:6466:15)
    at Response.arrayBuffer (node:internal/deps/undici/undici:6361:18)
    at $fetchRaw2 (file:///Users/ryanwang/Library/pnpm/store/v3/tmp/dlx-2942/node_modules/.pnpm/ofetch@1.0.1/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:198:68)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAvatarDataURI (file:///Users/ryanwang/Library/pnpm/store/v3/tmp/dlx-2942/node_modules/.pnpm/make-github-contributor-svg@1.0.1/node_modules/make-github-contributor-svg/lib/main.js:248:22)
    at async file:///Users/ryanwang/Library/pnpm/store/v3/tmp/dlx-2942/node_modules/.pnpm/make-github-contributor-svg@1.0.1/node_modules/make-github-contributor-svg/lib/main.js:307:29
    at async Promise.all (index 97)
    at async generateContributorsSVGFile (file:///Users/ryanwang/Library/pnpm/store/v3/tmp/dlx-2942/node_modules/.pnpm/make-github-contributor-svg@1.0.1/node_modules/make-github-contributor-svg/lib/main.js:305:3)
    at async main (file:///Users/ryanwang/Library/pnpm/store/v3/tmp/dlx-2942/node_modules/.pnpm/make-github-contributor-svg@1.0.1/node_modules/make-github-contributor-svg/lib/main.js:368:23)

Node.js v18.15.0
 ERROR  Command failed with exit code 1: gh-contrib-svg -t <打码> -o halo-dev -r halo

pnpm: Command failed with exit code 1: gh-contrib-svg -t <打码> -o halo-dev -r halo
    at makeError (/Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:23113:17)
    at handlePromise (/Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:23684:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:218968:7)
    at async /Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:226695:21
    at async main (/Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:226662:34)
    at async runPnpm (/Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:226894:5)
    at async /Users/ryanwang/Library/pnpm/global/5/.pnpm/pnpm@7.28.0/node_modules/pnpm/dist/pnpm.cjs:226886:7

```

system info:

```bash
❯ npx envinfo --system --binaries --browsers

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 358.48 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1
    Safari: 16.3
```

**Comment by ShenQingchuan** [comment]
After discussion with @ruibaby , it was found that it may be an environmental issue and cannot be reproduced temporarily.

Feel free to reopen this issue if anyone encountered in the same problem.
